import {
  User,
  Business,
  Employee,
  Service,
  Appointment,
  Client,
  Payment,
} from "./types";
import { addDays, format, subDays } from "date-fns";

const today = new Date();
const todayStr = format(today, "yyyy-MM-dd");
const tomorrowStr = format(addDays(today, 1), "yyyy-MM-dd");
const dayAfterStr = format(addDays(today, 2), "yyyy-MM-dd");
const threeDaysStr = format(addDays(today, 3), "yyyy-MM-dd");
const yesterdayStr = format(subDays(today, 1), "yyyy-MM-dd");
const twoDaysAgoStr = format(subDays(today, 2), "yyyy-MM-dd");
const weekAgoStr = format(subDays(today, 7), "yyyy-MM-dd");

// ─── Users ───────────────────────────────────────────────────────────────────
export const USERS: User[] = [
  {
    id: "u1",
    name: "Carlos Mendoza",
    email: "negocio@demo.com",
    password: "123456",
    role: "business",
    businessId: "b1",
  },
  {
    id: "u2",
    name: "Ana García",
    email: "cliente@demo.com",
    password: "123456",
    role: "client",
    clientId: "c1",
  },
  {
    id: "u3",
    name: "Roberto Pérez",
    email: "roberto@test.com",
    password: "123456",
    role: "client",
    clientId: "c2",
  },
];

// ─── Business ────────────────────────────────────────────────────────────────
export const BUSINESSES: Business[] = [
  {
    id: "b1",
    name: "Barbería Elite",
    slug: "demo",
    tagline: "El mejor servicio de barbería premium",
    category: "Barbería",
    address: "Av. Reforma 123, Col. Centro, CDMX",
    phone: "+52 55 1234 5678",
    email: "contacto@barberiaelite.com",
    coverColor: "#4228d9",
    ownerId: "u1",
  },
];

// ─── Employees ───────────────────────────────────────────────────────────────
export const EMPLOYEES: Employee[] = [
  {
    id: "e1",
    businessId: "b1",
    name: "Miguel Torres",
    specialty: "Cortes clásicos & degradados",
    color: "#6050f8",
    avatar: "MT",
    workDays: [1, 2, 3, 4, 5, 6],
    startHour: 9,
    endHour: 19,
    active: true,
  },
  {
    id: "e2",
    businessId: "b1",
    name: "Luis Rodríguez",
    specialty: "Barba & afeitado clásico",
    color: "#06b6d4",
    avatar: "LR",
    workDays: [1, 2, 3, 4, 5, 6],
    startHour: 10,
    endHour: 20,
    active: true,
  },
  {
    id: "e3",
    businessId: "b1",
    name: "Andrea Vega",
    specialty: "Coloración & cuidado capilar",
    color: "#f59e0b",
    avatar: "AV",
    workDays: [2, 3, 4, 5, 6],
    startHour: 9,
    endHour: 18,
    active: true,
  },
];

// ─── Services ─────────────────────────────────────────────────────────────────
export const SERVICES: Service[] = [
  {
    id: "s1",
    businessId: "b1",
    name: "Corte clásico",
    description: "Corte con tijeras o máquina, incluye lavado",
    duration: 30,
    price: 180,
    category: "Corte",
    active: true,
  },
  {
    id: "s2",
    businessId: "b1",
    name: "Corte + Barba",
    description: "Corte completo más arreglo y perfilado de barba",
    duration: 50,
    price: 280,
    category: "Combo",
    active: true,
  },
  {
    id: "s3",
    businessId: "b1",
    name: "Afeitado clásico",
    description: "Afeitado con navaja y toalla caliente",
    duration: 30,
    price: 150,
    category: "Barba",
    active: true,
  },
  {
    id: "s4",
    businessId: "b1",
    name: "Coloración completa",
    description: "Tinte, aclarado o mechas. Incluye tratamiento",
    duration: 120,
    price: 650,
    category: "Color",
    active: true,
  },
  {
    id: "s5",
    businessId: "b1",
    name: "Tratamiento capilar",
    description: "Hidratación profunda con mascarilla premium",
    duration: 45,
    price: 320,
    category: "Tratamiento",
    active: true,
  },
  {
    id: "s6",
    businessId: "b1",
    name: "Kids Corte",
    description: "Corte infantil hasta 12 años",
    duration: 20,
    price: 120,
    category: "Corte",
    active: true,
  },
];

// ─── Clients ─────────────────────────────────────────────────────────────────
export const CLIENTS: Client[] = [
  {
    id: "c1",
    businessId: "b1",
    name: "Ana García",
    email: "cliente@demo.com",
    phone: "+52 55 9876 5432",
    notes: "Prefiere coloración oscura. Alérgica al amoniaco.",
    totalVisits: 8,
    totalSpent: 2840,
    lastVisit: yesterdayStr,
    createdAt: "2024-06-01",
  },
  {
    id: "c2",
    businessId: "b1",
    name: "Roberto Pérez",
    email: "roberto@test.com",
    phone: "+52 55 1111 2222",
    notes: "Siempre pide a Miguel. Corte degradado bajo.",
    totalVisits: 12,
    totalSpent: 3360,
    lastVisit: twoDaysAgoStr,
    createdAt: "2024-03-15",
  },
  {
    id: "c3",
    businessId: "b1",
    name: "José Hernández",
    email: "jose.hdz@mail.com",
    phone: "+52 55 3333 4444",
    notes: "",
    totalVisits: 5,
    totalSpent: 1400,
    lastVisit: weekAgoStr,
    createdAt: "2024-08-20",
  },
  {
    id: "c4",
    businessId: "b1",
    name: "María López",
    email: "maria.l@mail.com",
    phone: "+52 55 5555 6666",
    notes: "Tratamiento mensual. Cabello muy seco.",
    totalVisits: 6,
    totalSpent: 1920,
    lastVisit: weekAgoStr,
    createdAt: "2024-07-10",
  },
  {
    id: "c5",
    businessId: "b1",
    name: "Fernando Castro",
    email: "fcastro@mail.com",
    phone: "+52 55 7777 8888",
    notes: "",
    totalVisits: 3,
    totalSpent: 840,
    lastVisit: format(subDays(today, 14), "yyyy-MM-dd"),
    createdAt: "2024-10-05",
  },
  {
    id: "c6",
    businessId: "b1",
    name: "Daniela Morales",
    email: "dani.morales@mail.com",
    phone: "+52 55 9999 0000",
    notes: "Nueva clienta. Viene referida por Ana García.",
    totalVisits: 2,
    totalSpent: 800,
    lastVisit: format(subDays(today, 3), "yyyy-MM-dd"),
    createdAt: "2024-11-20",
  },
];

// ─── Appointments ─────────────────────────────────────────────────────────────
export const APPOINTMENTS: Appointment[] = [
  // Today's appointments
  {
    id: "a1",
    businessId: "b1",
    clientId: "c2",
    clientName: "Roberto Pérez",
    clientEmail: "roberto@test.com",
    clientPhone: "+52 55 1111 2222",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s2",
    serviceName: "Corte + Barba",
    servicePrice: 280,
    serviceDuration: 50,
    date: todayStr,
    time: "10:00",
    status: "confirmada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: yesterdayStr,
  },
  {
    id: "a2",
    businessId: "b1",
    clientId: "c1",
    clientName: "Ana García",
    clientEmail: "cliente@demo.com",
    clientPhone: "+52 55 9876 5432",
    employeeId: "e3",
    employeeName: "Andrea Vega",
    serviceId: "s4",
    serviceName: "Coloración completa",
    servicePrice: 650,
    serviceDuration: 120,
    date: todayStr,
    time: "11:00",
    status: "confirmada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: twoDaysAgoStr,
  },
  {
    id: "a3",
    businessId: "b1",
    clientId: "c3",
    clientName: "José Hernández",
    clientEmail: "jose.hdz@mail.com",
    clientPhone: "+52 55 3333 4444",
    employeeId: "e2",
    employeeName: "Luis Rodríguez",
    serviceId: "s3",
    serviceName: "Afeitado clásico",
    servicePrice: 150,
    serviceDuration: 30,
    date: todayStr,
    time: "13:00",
    status: "pendiente",
    paymentStatus: "pendiente",
    createdAt: todayStr,
  },
  {
    id: "a4",
    businessId: "b1",
    clientId: "c5",
    clientName: "Fernando Castro",
    clientEmail: "fcastro@mail.com",
    clientPhone: "+52 55 7777 8888",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s1",
    serviceName: "Corte clásico",
    servicePrice: 180,
    serviceDuration: 30,
    date: todayStr,
    time: "15:00",
    status: "pendiente",
    paymentStatus: "pendiente",
    createdAt: todayStr,
  },
  // Tomorrow
  {
    id: "a5",
    businessId: "b1",
    clientId: "c4",
    clientName: "María López",
    clientEmail: "maria.l@mail.com",
    clientPhone: "+52 55 5555 6666",
    employeeId: "e3",
    employeeName: "Andrea Vega",
    serviceId: "s5",
    serviceName: "Tratamiento capilar",
    servicePrice: 320,
    serviceDuration: 45,
    date: tomorrowStr,
    time: "10:00",
    status: "confirmada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: todayStr,
  },
  {
    id: "a6",
    businessId: "b1",
    clientId: "c6",
    clientName: "Daniela Morales",
    clientEmail: "dani.morales@mail.com",
    clientPhone: "+52 55 9999 0000",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s2",
    serviceName: "Corte + Barba",
    servicePrice: 280,
    serviceDuration: 50,
    date: tomorrowStr,
    time: "14:00",
    status: "confirmada",
    paymentStatus: "pagado",
    paymentMethod: "efectivo",
    createdAt: todayStr,
  },
  // Day after tomorrow
  {
    id: "a7",
    businessId: "b1",
    clientId: "c2",
    clientName: "Roberto Pérez",
    clientEmail: "roberto@test.com",
    clientPhone: "+52 55 1111 2222",
    employeeId: "e2",
    employeeName: "Luis Rodríguez",
    serviceId: "s3",
    serviceName: "Afeitado clásico",
    servicePrice: 150,
    serviceDuration: 30,
    date: dayAfterStr,
    time: "11:30",
    status: "pendiente",
    paymentStatus: "pendiente",
    createdAt: todayStr,
  },
  {
    id: "a8",
    businessId: "b1",
    clientId: "c3",
    clientName: "José Hernández",
    clientEmail: "jose.hdz@mail.com",
    clientPhone: "+52 55 3333 4444",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s1",
    serviceName: "Corte clásico",
    servicePrice: 180,
    serviceDuration: 30,
    date: threeDaysStr,
    time: "09:00",
    status: "confirmada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: todayStr,
  },
  // Past appointments
  {
    id: "a9",
    businessId: "b1",
    clientId: "c1",
    clientName: "Ana García",
    clientEmail: "cliente@demo.com",
    clientPhone: "+52 55 9876 5432",
    employeeId: "e3",
    employeeName: "Andrea Vega",
    serviceId: "s5",
    serviceName: "Tratamiento capilar",
    servicePrice: 320,
    serviceDuration: 45,
    date: yesterdayStr,
    time: "10:00",
    status: "completada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: format(subDays(today, 3), "yyyy-MM-dd"),
  },
  {
    id: "a10",
    businessId: "b1",
    clientId: "c4",
    clientName: "María López",
    clientEmail: "maria.l@mail.com",
    clientPhone: "+52 55 5555 6666",
    employeeId: "e3",
    employeeName: "Andrea Vega",
    serviceId: "s4",
    serviceName: "Coloración completa",
    servicePrice: 650,
    serviceDuration: 120,
    date: twoDaysAgoStr,
    time: "13:00",
    status: "completada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: format(subDays(today, 5), "yyyy-MM-dd"),
  },
  {
    id: "a11",
    businessId: "b1",
    clientId: "c5",
    clientName: "Fernando Castro",
    clientEmail: "fcastro@mail.com",
    clientPhone: "+52 55 7777 8888",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s1",
    serviceName: "Corte clásico",
    servicePrice: 180,
    serviceDuration: 30,
    date: weekAgoStr,
    time: "15:00",
    status: "completada",
    paymentStatus: "pagado",
    paymentMethod: "efectivo",
    createdAt: format(subDays(today, 9), "yyyy-MM-dd"),
  },
  {
    id: "a12",
    businessId: "b1",
    clientId: "c2",
    clientName: "Roberto Pérez",
    clientEmail: "roberto@test.com",
    clientPhone: "+52 55 1111 2222",
    employeeId: "e1",
    employeeName: "Miguel Torres",
    serviceId: "s2",
    serviceName: "Corte + Barba",
    servicePrice: 280,
    serviceDuration: 50,
    date: twoDaysAgoStr,
    time: "11:00",
    status: "completada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: format(subDays(today, 5), "yyyy-MM-dd"),
  },
  {
    id: "a13",
    businessId: "b1",
    clientId: "c6",
    clientName: "Daniela Morales",
    clientEmail: "dani.morales@mail.com",
    clientPhone: "+52 55 9999 0000",
    employeeId: "e3",
    employeeName: "Andrea Vega",
    serviceId: "s5",
    serviceName: "Tratamiento capilar",
    servicePrice: 320,
    serviceDuration: 45,
    date: format(subDays(today, 3), "yyyy-MM-dd"),
    time: "14:30",
    status: "completada",
    paymentStatus: "pagado",
    paymentMethod: "tarjeta",
    createdAt: format(subDays(today, 6), "yyyy-MM-dd"),
  },
  {
    id: "a14",
    businessId: "b1",
    clientId: "c3",
    clientName: "José Hernández",
    clientEmail: "jose.hdz@mail.com",
    clientPhone: "+52 55 3333 4444",
    employeeId: "e2",
    employeeName: "Luis Rodríguez",
    serviceId: "s3",
    serviceName: "Afeitado clásico",
    servicePrice: 150,
    serviceDuration: 30,
    date: weekAgoStr,
    time: "12:00",
    status: "cancelada",
    paymentStatus: "pendiente",
    createdAt: format(subDays(today, 10), "yyyy-MM-dd"),
  },
];

export const PAYMENTS: Payment[] = APPOINTMENTS.filter(
  (a) => a.paymentStatus === "pagado",
).map((a) => ({
  id: `p-${a.id}`,
  appointmentId: a.id,
  amount: a.servicePrice,
  method: a.paymentMethod || "tarjeta",
  status: "pagado" as const,
  date: a.date,
}));
